[package]
name = "rustls-cng"
version = "0.3.2"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Windows CNG API bridge for rustls"
license = "MIT/Apache-2.0"
repository = "https://github.com/ancwrd1/rustls-cng"
documentation = "https://ancwrd1.github.io/rustls-cng/doc/rustls_cng"
readme = "README.md"
keywords = ["cng", "tls", "rustls", "windows"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-gnu", "x86_64-pc-windows-msvc"]

[dependencies]
rustls = "0.21"
sha2 = "0.10"
windows = { version = "0.48", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }
widestring = "1"
thiserror = "1"
hex = "0.4"

[dev-dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
